class WeaponData:
    # Reference data for weapons so we can assign them to a faction
    WEAPONS: dict[str, dict[str, str]] = {
        # US Infantry
        'M1A1 THOMPSON': {'side':'Allies','faction':'US','group':'Infantry'},
        'M3 GREASE GUN': {'side':'Allies','faction':'US','group':'Infantry'},
        'M1 GARAND': {'side':'Allies','faction':'US','group':'Infantry'},
        'M1 CARBINE': {'side':'Allies','faction':'US','group':'Infantry'},
        'M1918A2 BAR': {'side':'Allies','faction':'US','group':'Infantry'},
        'M97 TRENCH GUN': {'side':'Allies','faction':'US','group':'Infantry'},
        'BROWNING M1919': {'side':'Allies','faction':'US','group':'Infantry'},
        'M1903 SPRINGFIELD': {'side':'Allies','faction':'US','group':'Infantry'},
        'COLT M1911': {'side':'Allies','faction':'US','group':'Infantry'},
        'M2 FLAMETHROWER': {'side':'Allies','faction':'US','group':'Infantry'},
        'M3 KNIFE': {'side':'Allies','faction':'US','group':'Infantry'},
        'MK2 GRENADE': {'side':'Allies','faction':'US','group':'Infantry'},
        'M2 AP MINE': {'side':'Allies','faction':'US','group':'Infantry'},
        'M1A1 AT MINE': {'side':'Allies','faction':'US','group':'Infantry'},
        'BAZOOKA': {'side':'Allies','faction':'US','group':'Infantry'},
        '57MM CANNON [M1 57mm]': {'side':'Allies','faction':'US','group':'Infantry'},
        'M3 Half-track': {'side':'Allies','faction':'US','group':'Infantry'},
        'M2 Browning [M3 Half-track]': {'side':'Allies','faction':'US','group':'Infantry'},
        'GMC CCKW 353 (Transport)': {'side':'Allies','faction':'US','group':'Infantry'},
        'GMC CCKW 353 (Supply)': {'side':'Allies','faction':'US','group':'Infantry'},
        'Jeep Willys': {'side':'Allies','faction':'US','group':'Infantry'},

        # US Artillery
        '155MM HOWITZER [M114]': {'side':'Allies','faction':'US','group':'Artillery'},

        # US Armor
        'M8 Greyhound': {'side':'Allies','faction':'US','group':'Armor'},
        'M6 37mm [M8 Greyhound]': {'side':'Allies','faction':'US','group':'Armor'},
        'COAXIAL M1919 [M8 Greyhound]': {'side':'Allies','faction':'US','group':'Armor'},
        'Stuart M5A1': {'side':'Allies','faction':'US','group':'Armor'},
        '37MM CANNON [Stuart M5A1]': {'side':'Allies','faction':'US','group':'Armor'},
        'COAXIAL M1919 [Stuart M5A1]': {'side':'Allies','faction':'US','group':'Armor'},
        'HULL M1919 [Stuart M5A1]': {'side':'Allies','faction':'US','group':'Armor'},
        'Sherman M4A3(75)W': {'side':'Allies','faction':'US','group':'Armor'},
        '75MM CANNON [Sherman M4A3(75)W]': {'side':'Allies','faction':'US','group':'Armor'},
        'COAXIAL M1919 [Sherman M4A3(75)W]': {'side':'Allies','faction':'US','group':'Armor'},
        'HULL M1919 [Sherman M4A3(75)W]': {'side':'Allies','faction':'US','group':'Armor'},
        'Sherman M4A3E2': {'side':'Allies','faction':'US','group':'Armor'},
        '75MM M3 GUN [Sherman M4A3E2]': {'side':'Allies','faction':'US','group':'Armor'},
        'COAXIAL M1919 [Sherman M4A3E2]': {'side':'Allies','faction':'US','group':'Armor'},
        'HULL M1919 [Sherman M4A3E2]': {'side':'Allies','faction':'US','group':'Armor'},
        'Sherman M4A3E2(76)': {'side':'Allies','faction':'US','group':'Armor'},
        '76MM M1 GUN [Sherman M4A3E2(76)]': {'side':'Allies','faction':'US','group':'Armor'},
        'COAXIAL M1919 [Sherman M4A3E2(76)]': {'side':'Allies','faction':'US','group':'Armor'},
        'HULL M1919 [Sherman M4A3E2(76)]': {'side':'Allies','faction':'US','group':'Armor'},

        # GER Infantry
        'MP40': {'side':'Axis','faction':'GER','group':'Infantry'},
        'GEWEHR 43': {'side':'Axis','faction':'GER','group':'Infantry'},
        'KARABINER 98K': {'side':'Axis','faction':'GER','group':'Infantry'},
        'STG44': {'side':'Axis','faction':'GER','group':'Infantry'},
        'FG42': {'side':'Axis','faction':'GER','group':'Infantry'},
        'MG34': {'side':'Axis','faction':'GER','group':'Infantry'},
        'MG42': {'side':'Axis','faction':'GER','group':'Infantry'},
        'KARABINER 98K x8': {'side':'Axis','faction':'GER','group':'Infantry'},
        'FG42 x4': {'side':'Axis','faction':'GER','group':'Infantry'},
        'WALTHER P38': {'side':'Axis','faction':'GER','group':'Infantry'},
        'LUGER P08': {'side':'Axis','faction':'GER','group':'Infantry'},
        'FLAMMENWERFER 41': {'side':'Axis','faction':'GER','group':'Infantry'},
        'FELDSPATEN': {'side':'Axis','faction':'GER','group':'Infantry'},
        'M24 STIELHANDGRANATE': {'side':'Axis','faction':'GER','group':'Infantry'},
        'M43 STIELHANDGRANATE': {'side':'Axis','faction':'GER','group':'Infantry'},
        'S-MINE': {'side':'Axis','faction':'GER','group':'Infantry'},
        'TELLERMINE 43': {'side':'Axis','faction':'GER','group':'Infantry'},
        'PANZERSCHRECK': {'side':'Axis','faction':'GER','group':'Infantry'},
        '75MM CANNON [PAK 40]': {'side':'Axis','faction':'GER','group':'Infantry'},
        'Sd.Kfz 251 Half-track': {'side':'Axis','faction':'GER','group':'Infantry'},
        'MG 42 [Sd.Kfz 251 Half-track]': {'side':'Axis','faction':'GER','group':'Infantry'},
        'Opel Blitz (Transport)': {'side':'Axis','faction':'GER','group':'Infantry'},
        'Opel Blitz (Supply)': {'side':'Axis','faction':'GER','group':'Infantry'},
        'Kubelwagen': {'side':'Axis','faction':'GER','group':'Infantry'},

        # GER Artillery
        '150MM HOWITZER [sFH 18]': {'side':'Axis','faction':'GER','group':'Artillery'},

        # GER Armor
        'Sd.Kfz.234 Puma': {'side':'Axis','faction':'GER','group':'Armor'},
        '50mm KwK 39/1 [Sd.Kfz.234 Puma]': {'side':'Axis','faction':'GER','group':'Armor'},
        'COAXIAL MG34 [Sd.Kfz.234 Puma]': {'side':'Axis','faction':'GER','group':'Armor'},
        'Sd.Kfz.121 Luchs': {'side':'Axis','faction':'GER','group':'Armor'},
        '20MM KWK 30 [Sd.Kfz.121 Luchs]': {'side':'Axis','faction':'GER','group':'Armor'},
        'COAXIAL MG34 [Sd.Kfz.121 Luchs]': {'side':'Axis','faction':'GER','group':'Armor'},
        'Sd.Kfz.161 Panzer IV': {'side':'Axis','faction':'GER','group':'Armor'},
        '75MM CANNON [Sd.Kfz.161 Panzer IV]': {'side':'Axis','faction':'GER','group':'Armor'},
        'COAXIAL MG34 [Sd.Kfz.161 Panzer IV]': {'side':'Axis','faction':'GER','group':'Armor'},
        'HULL MG34 [Sd.Kfz.161 Panzer IV]': {'side':'Axis','faction':'GER','group':'Armor'},
        'Sd.Kfz.181 Tiger 1': {'side':'Axis','faction':'GER','group':'Armor'},
        '88 KWK 36 L/56 [Sd.Kfz.181 Tiger 1]': {'side':'Axis','faction':'GER','group':'Armor'},
        'COAXIAL MG34 [Sd.Kfz.181 Tiger 1]': {'side':'Axis','faction':'GER','group':'Armor'},
        'HULL MG34 [Sd.Kfz.181 Tiger 1]': {'side':'Axis','faction':'GER','group':'Armor'},
        'Sd.Kfz.171 Panther': {'side':'Axis','faction':'GER','group':'Armor'},
        '75MM CANNON [Sd.Kfz.171 Panther]': {'side':'Axis','faction':'GER','group':'Armor'},
        'COAXIAL MG34 [Sd.Kfz.171 Panther]': {'side':'Axis','faction':'GER','group':'Armor'},
        'HULL MG34 [Sd.Kfz.171 Panther]': {'side':'Axis','faction':'GER','group':'Armor'},

        # RUS Infantry
        'PPSH 41': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'PPSH 41 W/DRUM': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'SVT40': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'MOSIN NAGANT 1891': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'MOSIN NAGANT 91/30': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'MOSIN NAGANT M38': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'DP-27': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'SCOPED MOSIN NAGANT 91/30': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'SCOPED SVT40': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'NAGANT M1895': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'TOKAREV TT33': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'MPL-50 SPADE': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'RG-42 GRENADE': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'MOLOTOV': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'POMZ AP MINE': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'TM-35 AT MINE': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'PTRS-41': {'side':'Allies','faction':'RUS','group':'Infantry'},
        # BAZOOKA is already categorized as US
        '57MM CANNON [ZiS-2]': {'side':'Allies','faction':'RUS','group':'Infantry'},
        # M3 Half-track is already categorized as US
        'ZIS-5 (Transport)': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'ZIS-5 (Supply)': {'side':'Allies','faction':'RUS','group':'Infantry'},
        'GAZ-67': {'side':'Allies','faction':'RUS','group':'Infantry'},

        # RUS Artillery
        '122MM HOWITZER [M1938 (M-30)]': {'side':'Allies','faction':'RUS','group':'Artillery'},

        # RUS Armor
        'BA-10': {'side':'Allies','faction':'RUS','group':'Armor'},
        '19-K 45MM [BA-10]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'COAXIAL DT [BA-10]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'T70': {'side':'Allies','faction':'RUS','group':'Armor'},
        '45MM M1937 [T70]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'COAXIAL DT [T70]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'T34/76': {'side':'Allies','faction':'RUS','group':'Armor'},
        '76MM ZiS-5 [T34/76]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'COAXIAL DT [T34/76]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'HULL DT [T34/76]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'IS-1': {'side':'Allies','faction':'RUS','group':'Armor'},
        'D-5T 85MM [IS-1]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'COAXIAL DT [IS-1]': {'side':'Allies','faction':'RUS','group':'Armor'},
        'HULL DT [IS-1]': {'side':'Allies','faction':'RUS','group':'Armor'},

        # GB Infantry
        'Sten Gun Mk.II': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Sten Gun Mk.V': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Lanchester': {'side':'Allies','faction':'GB','group':'Infantry'},
        'M1928A1 THOMPSON': {'side':'Allies','faction':'GB','group':'Infantry'},
        'SMLE No.1 Mk III': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Rifle No.4 Mk I': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Rifle No.5 Mk I': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Bren Gun': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Lewis Gun': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Lee-Enfield Pattern 1914 Sniper': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Rifle No.4 Mk I Sniper': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Webley MK VI': {'side':'Allies','faction':'GB','group':'Infantry'},
        'FLAMETHROWER': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Fairbairn–Sykes': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Mills Bomb': {'side':'Allies','faction':'GB','group':'Infantry'},
        'No.82 Grenade': {'side':'Allies','faction':'GB','group':'Infantry'},
        'A.P. Shrapnel Mine Mk II': {'side':'Allies','faction':'GB','group':'Infantry'},
        'A.T. Mine G.S. Mk V': {'side':'Allies','faction':'GB','group':'Infantry'},
        'PIAT': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Boys Anti-tank Rifle': {'side':'Allies','faction':'GB','group':'Infantry'},
        'QF 6-POUNDER [QF 6-Pounder]': {'side':'Allies','faction':'GB','group':'Infantry'},
        # M3 Half-track is already categorized as US
        'Bedford OYD (Transport)': {'side':'Allies','faction':'GB','group':'Infantry'},
        'Bedford OYD (Supply)': {'side':'Allies','faction':'GB','group':'Infantry'},
        # Jeep Willys is already categorized as US

        # GB Artillery
        'QF 25-POUNDER [QF 25-Pounder]': {'side':'Allies','faction':'GB','group':'Artillery'},

        # GB Armor
        'Daimler': {'side':'Allies','faction':'GB','group':'Armor'},
        'QF 2-POUNDER [Daimler]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL BESA [Daimler]': {'side':'Allies','faction':'GB','group':'Armor'},
        'Tetrarch': {'side':'Allies','faction':'GB','group':'Armor'},
        'QF 2-POUNDER [Tetrarch]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL BESA [Tetrarch]': {'side':'Allies','faction':'GB','group':'Armor'},
        'M3 Stuart Honey': {'side':'Allies','faction':'GB','group':'Armor'},
        '37MM CANNON [M3 Stuart Honey]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL M1919 [M3 Stuart Honey]': {'side':'Allies','faction':'GB','group':'Armor'},
        'HULL M1919 [M3 Stuart Honey]': {'side':'Allies','faction':'GB','group':'Armor'},
        'Cromwell': {'side':'Allies','faction':'GB','group':'Armor'},
        'QF 75MM [Cromwell]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL BESA [Cromwell]': {'side':'Allies','faction':'GB','group':'Armor'},
        'HULL BESA [Cromwell]': {'side':'Allies','faction':'GB','group':'Armor'},
        'Crusader Mk.III': {'side':'Allies','faction':'GB','group':'Armor'},
        'OQF 57MM [Crusader Mk.III]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL BESA [Crusader Mk.III]': {'side':'Allies','faction':'GB','group':'Armor'},
        'Firefly': {'side':'Allies','faction':'GB','group':'Armor'},
        'QF 17-POUNDER [Firefly]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL M1919 [Firefly]': {'side':'Allies','faction':'GB','group':'Armor'},
        'Churchill Mk.III': {'side':'Allies','faction':'GB','group':'Armor'},
        'OQF 57MM [Churchill Mk.III]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL BESA 7.92mm [Churchill Mk.III]': {'side':'Allies','faction':'GB','group':'Armor'},
        'HULL BESA 7.92mm [Churchill Mk.III]': {'side':'Allies','faction':'GB','group':'Armor'},
        'Churchill Mk.VII': {'side':'Allies','faction':'GB','group':'Armor'},
        'OQF 57MM [Churchill Mk.VII]': {'side':'Allies','faction':'GB','group':'Armor'},
        'COAXIAL BESA 7.92mm [Churchill Mk.VII]': {'side':'Allies','faction':'GB','group':'Armor'},
        'HULL BESA 7.92mm [Churchill Mk.VII]': {'side':'Allies','faction':'GB','group':'Armor'}
    }

    MACHINE_GUNS: set[str] = {
        'BROWNING M1919', 'MG34', 'MG42', 'DP-27', 'Lewis Gun'
    }
